name: ExcerciseWorkflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./viikko1/riippuvuuksien-injektointi-1

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Move to folder
        run: |
          pwd
          ls -la
        working-directory: ${{env.working-directory}}  