name: ExcerciseWorkflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./viikko1/riippuvuuksien-injektointi-1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install Poetry and deps
        run: | 
          pip install poetry
          poetry install
        working-directory: ${{env.working-directory}}

      - name: Run tests
        run: poetry run python3 ./src/index.py
        working-directory: ${{env.working-directory}}