name: ExcerciseWorkflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Poetry
        working-directory: ./viikko1/riippuvuuksien-injektointi-1
        run: pip install poetry
      - name: Install dependencies
        working-directory: ./viikko1/riippuvuuksien-injektointi-1
        run: poetry install
      - name: Run tests
        working-directory: ./viikko1/riippuvuuksien-injektointi-1
        run: poetry run coverage run --branch -m pytest
      - name: Coverage report
        working-directory: ./viikko1/riippuvuuksien-injektointi-1
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        working-directory: ./viikko1/riippuvuuksien-injektointi-1
        run: bash <(curl -s https://codecov.io/bash)
